### ISSUE TITLE
Data Preparation and Split for CNN

### ISSUE THREAD

**Issue by aqibsaeed** [Eldave93/Seizure-Detection-Tutorials#2]
Hi Dave

Thanks for nice set of tutorials. Could you please share the script you used to prepare data for 1D CNN notebook? Also I do not quite understand how you read the training and test sets as in the original TUH EEG corpus there are training and test sets available.

**Comment by Eldave93** [comment]
Hi aqibsaeed,

Sorry for not responding in so long. 

I want to start focusing on this project again soon but my time since the end of August has been spent focusing on my new teaching role at Edinburgh University. However, my aim is to go over the data preparation script in December as I have received a few emails about this now and it was always my intention to make a separate tutorial just on this and go through it step by step. The data preparation scripts as they stand are still pretty messy and need tidying up. I also want to check it for errors, especially as more people have messaged me about them than I expected.

I am also going to be teaching an MSc course "Machine Learning in Python" next semester which gives me a good opportunity to improve these materials while I work on a more general machine learning course.

**Comment by sgopalan98** [comment]
Hi Dave,

Amazing set of tutorials and thanks of the new role in your university. I was also quite curious about the preparation of data for the 1D model. Can you brief on the steps that you had performed, if not the code, for it?

**Comment by Eldave93** [comment]
I've just added my rough script up today but, as noted in the readme and the notebook, if you intend to use it make sure to go over and check for errors (I haven't had loads of time to check it myself). I threw it together from different scripts lying around (originally the data was created in separate scripts on my old machine), so I've tried to make them more general, but in doing so I may have added some issues :')

**Comment by sgopalan98** [comment]
Thank you so much! :D I'll definitely take a look at it. :)
